| Horizon   | Outcome-based strategic bet                                                                                                                                    | Why / OKR link                                                                                                      |
| --------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------- |
| **NOW**   | **Create a personalised post-acute engagement experience that gives users a relevant reason to keep returning after their immediate anxiety need has passed.** | Supports **KR1: increase post-acute 180-day retention by 30%**.                                                     |
| **NOW**   | **Establish reliable, contextually timed re-engagement so post-acute users receive prompts when they are most likely to find them useful.**                    | Supports **KR2: increase weekly active usage among post-acute users by 25%**.                                       |
| **NOW**   | **Expand Fable's everyday wellbeing value beyond acute anxiety through recurring meditation, sleep, breathing and short-form wellness experiences.**           | Supports **KR1 and KR3: retention and premium renewal**.                                                            |
| **NEXT**  | **Improve app performance and reduce load-time friction.**                                                                                                     | Comes after proving the post-acute value proposition because faster access amplifies value but does not create it.  |
| **NEXT**  | **Redesign onboarding around Fable as an ongoing wellbeing companion.**                                                                                        | Once the post-acute proposition is validated, onboarding can set the right expectation from day one.                |
| **NEXT**  | **Test lightweight habit-forming mechanics.**                                                                                                                  | Habit mechanics should reinforce demonstrated user value rather than manufacture engagement before value is proven. |
| **NEXT**  | **Close accessibility gaps across the core experience.**                                                                                                       | Strengthens reach and usability without distracting from the immediate retention bet.                               |
| **NEXT**  | **Test wearable integration for established wellbeing routines.**                                                                                              | Worth exploring after recurring mobile engagement has been demonstrated.                                            |
| **LATER** | **Explore a web experience as an additional access channel.**                                                                                                  | A potential future bet once sustained post-acute demand is proven.                                                  |
| **LATER** | **Explore Spanish and Portuguese localisation.**                                                                                                               | Geographic expansion should follow validation of the retention model in existing markets.                           |
| **LATER** | **Reassess social/community experiences.**                                                                                                                     | A future bet only if individual personalised engagement proves insufficient for durable retention.                  |
| **LATER** | **Explore Fable for Teams.**                                                                                                                                   | Potential B2B growth bet, but it introduces a different buyer, customer and business model.                         |
| **LATER** | **Evaluate therapist matching separately from the core strategy.**                                                                                             | Requires an explicit decision about expanding toward clinical services.                                             |
| **LATER** | **Consider further acute/crisis functionality.**                                                                                                               | Fable already performs strongly in acute use; current strategy prioritises the unresolved post-acute problem.       |
